/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author PC14
 */
public class ViewRenta extends javax.swing.JPanel {

    /**
     * Creates new form ViewRenta
     */
    public ViewRenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_idrenta = new javax.swing.JLabel();
        jl_idcliente = new javax.swing.JLabel();
        jl_idpelicula = new javax.swing.JLabel();
        jl_formato = new javax.swing.JLabel();
        jl_costodia = new javax.swing.JLabel();
        jl_dias = new javax.swing.JLabel();
        jl_totalrenta = new javax.swing.JLabel();
        jtf_idrenta = new javax.swing.JTextField();
        jtf_idcliente = new javax.swing.JTextField();
        jtf_idpelicula = new javax.swing.JTextField();
        jtf_formato = new javax.swing.JTextField();
        jtf_costodia = new javax.swing.JTextField();
        jtf_dias = new javax.swing.JTextField();
        jtf_totalrenta = new javax.swing.JTextField();
        jbtn_primero = new javax.swing.JButton();
        jbtn_ultimo = new javax.swing.JButton();
        jbtn_anterior = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_nuevo = new javax.swing.JButton();

        jl_idrenta.setText("Id_renta");

        jl_idcliente.setText("Id_cliente");

        jl_idpelicula.setText("Id_pelicula");

        jl_formato.setText("Formato");

        jl_costodia.setText("Costo Dia");

        jl_dias.setText("Dias");

        jl_totalrenta.setText("Total_renta");

        jtf_idpelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idpeliculaActionPerformed(evt);
            }
        });

        jbtn_primero.setText("|<");

        jbtn_ultimo.setText(">|");
        jbtn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ultimoActionPerformed(evt);
            }
        });

        jbtn_anterior.setText("<");

        jbtn_siguiente.setText(">");

        jbtn_agregar.setText("Agregar");

        jbtn_eliminar.setText("Eliminar");

        jbtn_actualizar.setText("Actualizar");

        jbtn_nuevo.setText("Nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_idrenta)
                    .addComponent(jl_idcliente)
                    .addComponent(jl_idpelicula)
                    .addComponent(jl_formato)
                    .addComponent(jl_costodia)
                    .addComponent(jl_dias)
                    .addComponent(jl_totalrenta))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_totalrenta, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jtf_dias)
                    .addComponent(jtf_costodia)
                    .addComponent(jtf_formato)
                    .addComponent(jtf_idrenta)
                    .addComponent(jtf_idcliente)
                    .addComponent(jtf_idpelicula))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn_siguiente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_primero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn_ultimo)))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_actualizar)
                            .addComponent(jbtn_agregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_eliminar)
                            .addComponent(jbtn_nuevo))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_idrenta)
                    .addComponent(jtf_idrenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_idcliente)
                            .addComponent(jtf_idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_idpelicula)
                            .addComponent(jtf_idpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_formato)
                            .addComponent(jtf_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_primero)
                            .addComponent(jbtn_ultimo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_anterior)
                            .addComponent(jbtn_siguiente))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_agregar)
                            .addComponent(jbtn_eliminar))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_costodia)
                            .addComponent(jtf_costodia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_actualizar)
                            .addComponent(jbtn_nuevo))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_dias)
                    .addComponent(jtf_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_totalrenta)
                    .addComponent(jtf_totalrenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_idpeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idpeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idpeliculaActionPerformed

    private void jbtn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_ultimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_agregar;
    public javax.swing.JButton jbtn_anterior;
    public javax.swing.JButton jbtn_eliminar;
    public javax.swing.JButton jbtn_nuevo;
    public javax.swing.JButton jbtn_primero;
    public javax.swing.JButton jbtn_siguiente;
    public javax.swing.JButton jbtn_ultimo;
    public javax.swing.JLabel jl_costodia;
    public javax.swing.JLabel jl_dias;
    public javax.swing.JLabel jl_formato;
    public javax.swing.JLabel jl_idcliente;
    public javax.swing.JLabel jl_idpelicula;
    public javax.swing.JLabel jl_idrenta;
    public javax.swing.JLabel jl_totalrenta;
    public javax.swing.JTextField jtf_costodia;
    public javax.swing.JTextField jtf_dias;
    public javax.swing.JTextField jtf_formato;
    public javax.swing.JTextField jtf_idcliente;
    public javax.swing.JTextField jtf_idpelicula;
    public javax.swing.JTextField jtf_idrenta;
    public javax.swing.JTextField jtf_totalrenta;
    // End of variables declaration//GEN-END:variables
}
